# Generated by Django 4.0.3 on 2022-04-14 17:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Введите вид животного', max_length=200, verbose_name='Животное')),
                ('age', models.CharField(help_text='Введите возраст животного', max_length=10, verbose_name='Возраст')),
                ('life_stage', models.CharField(help_text='Введите жизненный период животного', max_length=200, null=True, verbose_name='Период Животного')),
                ('weight_animal', models.DecimalField(decimal_places=2, help_text='Введите вес Животного', max_digits=2, null=True, verbose_name='Вес Животного')),
            ],
        ),
        migrations.CreateModel(
            name='StatusOfGoods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Введите статус товара', max_length=20, verbose_name='Статус товара')),
            ],
        ),
        migrations.CreateModel(
            name='TypeOfPackaging',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Введите название Фасовки', max_length=200, verbose_name='Фасовка')),
                ('type', models.CharField(default=1, help_text='Введите тип Фасовки', max_length=200, verbose_name='Тип Фасовки')),
                ('material', models.CharField(default=0, help_text='Введите материал Фасовки', max_length=200, verbose_name='Материал Фасовки')),
                ('weight', models.DecimalField(decimal_places=2, default=0, help_text='Введите вес Фасовки', max_digits=2, verbose_name='Вес Фасовки')),
            ],
        ),
        migrations.CreateModel(
            name='TypeOfMaterials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Введите тип Сырья', max_length=200, verbose_name='Тип Сырья')),
                ('packaging', models.ForeignKey(help_text='Выбрать Фасовку', null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.typeofpackaging', verbose_name='Фасовка')),
            ],
        ),
        migrations.CreateModel(
            name='TypeOfGoods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Введите Название Категории товара', max_length=200, verbose_name='Категория товара')),
                ('animal', models.ForeignKey(help_text='Выбрать Животное', null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.animal', verbose_name='Животное')),
                ('material', models.ForeignKey(help_text='Выбрать Сырьё', null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.typeofmaterials', verbose_name='Сырьё')),
            ],
        ),
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Введите название Товара', max_length=200, verbose_name='Название Товара')),
                ('price', models.CharField(help_text='Введите цену', max_length=100, verbose_name='Цена')),
                ('photo', models.ImageField(default=1, help_text='разместите фото', null=True, upload_to='images/goods/')),
                ('summary', models.TextField(help_text='Введите описание бленда', max_length=1000, verbose_name='Описание бленда')),
                ('animal', models.ForeignKey(help_text='Выберите Животное', null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.animal', verbose_name='Животное')),
                ('packaging', models.ForeignKey(help_text='Выбрать Фасовку', null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.typeofpackaging', verbose_name='Фасовка')),
                ('status', models.ForeignKey(help_text='Выбрать статус Товара', null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.statusofgoods', verbose_name='Статус Товара')),
                ('type_of_goods', models.ForeignKey(help_text='Выбрать тип продукта', null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.typeofgoods', verbose_name='Тип продукта')),
            ],
        ),
    ]
