# Generated by Django 4.0.3 on 2022-04-07 19:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TypeOfBlands',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Введите тип Бленда', max_length=200, verbose_name='Тип Бленда')),
            ],
        ),
        migrations.CreateModel(
            name='TypeOfGoods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Введите тип Продуктовой линейки', max_length=200, verbose_name='Продуктовая линейка')),
            ],
        ),
        migrations.CreateModel(
            name='TypeOfMaterials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Введите тип Сырья', max_length=200, verbose_name='Тип Сырья')),
            ],
        ),
        migrations.CreateModel(
            name='TypeOfPackaging',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Введите тип Фасовки', max_length=200, verbose_name='Тип Фасовки')),
            ],
        ),
        migrations.CreateModel(
            name='TypeOfPremix',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Введите тип Премикса', max_length=200, verbose_name='Тип Премикса')),
            ],
        ),
        migrations.CreateModel(
            name='Materials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Введите название сырья', max_length=200, verbose_name='Название сырья')),
                ('photo', models.ImageField(default=1, help_text='разместите фото', upload_to='images/materials/')),
                ('summary', models.TextField(help_text='Введите описание сырья', max_length=1000, verbose_name='Описание сырья')),
                ('price', models.CharField(help_text='Введите цену', max_length=100, verbose_name='Цена')),
                ('type', models.ForeignKey(help_text='Выбрать тип сырья', null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.typeofmaterials', verbose_name='тип сырья')),
                ('type_of_goods', models.ForeignKey(help_text='Выбрать тип продукта', null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.typeofgoods', verbose_name='Тип продукта')),
            ],
        ),
        migrations.CreateModel(
            name='Blands',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Введите название бленда', max_length=200, verbose_name='Название бленда')),
                ('photo', models.ImageField(default=1, help_text='разместите фото', upload_to='images/blands/')),
                ('summary', models.TextField(help_text='Введите описание бленда', max_length=1000, verbose_name='Описание бленда')),
                ('price', models.CharField(help_text='Введите цену', max_length=100, verbose_name='Цена')),
                ('type', models.ForeignKey(help_text='Выбрать тип бленда', null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.typeofblands', verbose_name='тип бленда')),
                ('type_of_goods', models.ForeignKey(help_text='Выбрать тип продукта', null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.typeofgoods', verbose_name='Тип продукта')),
            ],
        ),
    ]
