# Generated by Django 4.0.5 on 2022-06-30 16:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Birds',
            fields=[
                ('animal_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='catalog.animal')),
            ],
            options={
                'verbose_name': 'Птица',
                'verbose_name_plural': 'Птицы',
            },
            bases=('catalog.animal',),
        ),
        migrations.CreateModel(
            name='BirdsType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Введите тип птицы', max_length=200, verbose_name='Птица')),
            ],
        ),
        migrations.CreateModel(
            name='BVMK',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='catalog.product')),
            ],
            options={
                'verbose_name': 'БВМК',
                'verbose_name_plural': 'БВМК',
            },
            bases=('catalog.product',),
        ),
        migrations.CreateModel(
            name='Cows',
            fields=[
                ('animal_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='catalog.animal')),
            ],
            options={
                'verbose_name': 'Корова',
                'verbose_name_plural': 'Коровы',
            },
            bases=('catalog.animal',),
        ),
        migrations.CreateModel(
            name='Good',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=0, help_text='Введите название Товара', max_length=200, verbose_name='Название Товара')),
                ('image', models.IntegerField(default=0, help_text='Введите картинку продукта', verbose_name='Картинка')),
                ('price', models.DecimalField(decimal_places=2, default=0, help_text='Введите цену ', max_digits=10, verbose_name='Цена')),
            ],
        ),
        migrations.CreateModel(
            name='Industry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Kombikorm',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='catalog.product')),
            ],
            options={
                'verbose_name': 'Комбикорм',
                'verbose_name_plural': 'Комбикорм',
            },
            bases=('catalog.product',),
        ),
        migrations.CreateModel(
            name='Materials',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='catalog.product')),
            ],
            options={
                'verbose_name': 'Сырьё',
                'verbose_name_plural': 'Сырьё',
            },
            bases=('catalog.product',),
        ),
        migrations.CreateModel(
            name='Pig',
            fields=[
                ('animal_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='catalog.animal')),
            ],
            options={
                'verbose_name': 'Свинья',
                'verbose_name_plural': 'Свиньи',
            },
            bases=('catalog.animal',),
        ),
        migrations.CreateModel(
            name='Premix',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='catalog.product')),
            ],
            options={
                'verbose_name': 'Премикс',
                'verbose_name_plural': 'Премикс',
            },
            bases=('catalog.product',),
        ),
        migrations.CreateModel(
            name='TypeMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Введите тип сырья', max_length=200, verbose_name='Тип Сырья')),
            ],
        ),
        migrations.CreateModel(
            name='TypeOfIndustry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Введите Отрасль', max_length=50, verbose_name='Отрасль')),
            ],
        ),
        migrations.DeleteModel(
            name='Weight',
        ),
        migrations.RemoveField(
            model_name='animal',
            name='name',
        ),
        migrations.RemoveField(
            model_name='product',
            name='age',
        ),
        migrations.RemoveField(
            model_name='product',
            name='animal',
        ),
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.RemoveField(
            model_name='product',
            name='compound',
        ),
        migrations.RemoveField(
            model_name='product',
            name='input_percentage',
        ),
        migrations.RemoveField(
            model_name='product',
            name='name',
        ),
        migrations.RemoveField(
            model_name='product',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='summary',
        ),
        migrations.RemoveField(
            model_name='product',
            name='type',
        ),
        migrations.AddField(
            model_name='animal',
            name='animal_age_max',
            field=models.IntegerField(help_text='Введите максимальный Возраст', null=True, verbose_name='Максимальный Возраст'),
        ),
        migrations.AddField(
            model_name='animal',
            name='animal_age_min',
            field=models.IntegerField(help_text='Введите минимальный Возраст', null=True, verbose_name='Минимальный Возраст'),
        ),
        migrations.AddField(
            model_name='animal',
            name='weight_max',
            field=models.IntegerField(help_text='Выберите вес Животного (до)', null=True, verbose_name='Максимальный вес Животного'),
        ),
        migrations.AddField(
            model_name='animal',
            name='weight_min',
            field=models.IntegerField(help_text='Выберите вес Животного (от)', null=True, verbose_name='Минимальный вес Животного'),
        ),
        migrations.AddField(
            model_name='product',
            name='country',
            field=models.ForeignKey(help_text='Выберите страну изготовителя', null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.country', verbose_name='Страна изготовитель'),
        ),
        migrations.AddField(
            model_name='product',
            name='weight',
            field=models.IntegerField(help_text='Выберите вес продукта', null=True, verbose_name='Вес продукта'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='country',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='product',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.DeleteModel(
            name='Age',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='InputPercentage',
        ),
        migrations.DeleteModel(
            name='TypeOfGoods',
        ),
        migrations.AddField(
            model_name='materials',
            name='materials_type',
            field=models.ForeignKey(blank=True, help_text='Выберите тип Сырья', null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.typematerial', verbose_name='Сырьё'),
        ),
        migrations.AddField(
            model_name='industry',
            name='industry_animal',
            field=models.ForeignKey(help_text='Выберите Отрасль', null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.typeofindustry', verbose_name='Отрасль'),
        ),
        migrations.AddField(
            model_name='good',
            name='animal',
            field=models.ForeignKey(blank=True, help_text='Выберите Животное', null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.animal', verbose_name='Животное'),
        ),
        migrations.AddField(
            model_name='good',
            name='product',
            field=models.ForeignKey(help_text='Выберете продукт', null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.product', verbose_name='Продукт'),
        ),
        migrations.AddField(
            model_name='good',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AddField(
            model_name='birds',
            name='animal_type',
            field=models.ForeignKey(blank=True, help_text='Выберите тип Птицы', null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.birdstype', verbose_name='Птица'),
        ),
        migrations.AddField(
            model_name='animal',
            name='industry',
            field=models.ForeignKey(help_text='Выберите Отрасль', null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.industry', verbose_name='Отрасль'),
        ),
        migrations.AddField(
            model_name='product',
            name='industry',
            field=models.ForeignKey(help_text='Выберите Отрасль', null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.industry', verbose_name='Отрасль'),
        ),
    ]
