# Generated by Django 4.0.3 on 2022-04-08 19:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeOfPremixForBroiler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Введите тип Премикса для Бройлера', max_length=200, verbose_name='Тип Премикса Бройлер')),
            ],
        ),
        migrations.CreateModel(
            name='TypeOfPremixForPiglets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Введите тип Премикса для Поросят', max_length=200, verbose_name='Тип Премикса Поросята')),
            ],
        ),
        migrations.CreateModel(
            name='TypeOfPremixForPigs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Введите тип Премикса для Свиней', max_length=200, verbose_name='Тип Премикса Свиньи')),
            ],
        ),
        migrations.AddField(
            model_name='blands',
            name='type_of_packing',
            field=models.ForeignKey(help_text='Выбрать тип фасовки', null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.typeofpackaging', verbose_name='Тип фасовки'),
        ),
        migrations.AddField(
            model_name='materials',
            name='type_of_packing',
            field=models.ForeignKey(help_text='Выбрать тип фасовки', null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.typeofpackaging', verbose_name='Тип фасовки'),
        ),
        migrations.CreateModel(
            name='PremixForPiglets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Введите название премикса для Поросят', max_length=200, verbose_name='Название премикса для Поросят')),
                ('photo', models.ImageField(default=1, help_text='разместите фото', upload_to='images/premix/')),
                ('summary', models.TextField(help_text='Введите описание премикса', max_length=1000, verbose_name='Описание премикса')),
                ('price', models.CharField(help_text='Введите цену', max_length=100, verbose_name='Цена')),
                ('type_of_goods', models.ForeignKey(help_text='Выбрать тип продукта', null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.typeofgoods', verbose_name='Тип продукта')),
                ('type_of_packing', models.ForeignKey(help_text='Выбрать тип фасовки', null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.typeofpackaging', verbose_name='Тип фасовки')),
                ('type_of_premix', models.ForeignKey(help_text='Выбрать тип премикса', null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.typeofpremix', verbose_name='тип премикса')),
                ('type_premix_for_piglets', models.ForeignKey(help_text='Выбрать тип премикса для Поросят', null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.typeofpremixforpiglets', verbose_name='тип премикса для Поросят')),
            ],
        ),
        migrations.CreateModel(
            name='PremixForPig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Введите название премикса для Свиней', max_length=200, verbose_name='Название премикса для Свиней')),
                ('photo', models.ImageField(default=1, help_text='разместите фото', upload_to='images/premix/')),
                ('summary', models.TextField(help_text='Введите описание премикса', max_length=1000, verbose_name='Описание премикса')),
                ('price', models.CharField(help_text='Введите цену', max_length=100, verbose_name='Цена')),
                ('type_of_goods', models.ForeignKey(help_text='Выбрать тип продукта', null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.typeofgoods', verbose_name='Тип продукта')),
                ('type_of_packing', models.ForeignKey(help_text='Выбрать тип фасовки', null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.typeofpackaging', verbose_name='Тип фасовки')),
                ('type_of_premix', models.ForeignKey(help_text='Выбрать тип премикса', null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.typeofpremix', verbose_name='тип премикса')),
                ('type_premix_for_pigs', models.ForeignKey(help_text='Выбрать тип премикса для Свиней', null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.typeofpremixforpigs', verbose_name='тип премикса для Свиней')),
            ],
        ),
        migrations.CreateModel(
            name='PremixForCows',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Введите название премикса для KPC', max_length=200, verbose_name='Название премикса для KPC')),
                ('photo', models.ImageField(default=1, help_text='разместите фото', upload_to='images/premix/')),
                ('summary', models.TextField(help_text='Введите описание премикса', max_length=1000, verbose_name='Описание премикса')),
                ('price', models.CharField(help_text='Введите цену', max_length=100, verbose_name='Цена')),
                ('type_of_goods', models.ForeignKey(help_text='Выбрать тип продукта', null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.typeofgoods', verbose_name='Тип продукта')),
                ('type_of_packing', models.ForeignKey(help_text='Выбрать тип фасовки', null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.typeofpackaging', verbose_name='Тип фасовки')),
                ('type_of_premix', models.ForeignKey(help_text='Выбрать тип премикса', null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.typeofpremix', verbose_name='тип премикса')),
            ],
        ),
        migrations.CreateModel(
            name='PremixForBroiler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Введите название премикса для Бройлеров', max_length=200, verbose_name='Название премикса для Бройлеров')),
                ('photo', models.ImageField(default=1, help_text='разместите фото', upload_to='images/premix/')),
                ('summary', models.TextField(help_text='Введите описание премикса', max_length=1000, verbose_name='Описание премикса')),
                ('price', models.CharField(help_text='Введите цену', max_length=100, verbose_name='Цена')),
                ('type', models.ForeignKey(help_text='Выбрать тип премикса для Бройлеров', null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.typeofpremixforbroiler', verbose_name='тип премикса для Бройлеров')),
                ('type_of_goods', models.ForeignKey(help_text='Выбрать тип продукта', null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.typeofgoods', verbose_name='Тип продукта')),
                ('type_of_packing', models.ForeignKey(help_text='Выбрать тип фасовки', null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.typeofpackaging', verbose_name='Тип фасовки')),
                ('type_of_premix', models.ForeignKey(help_text='Выбрать тип премикса', null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.typeofpremix', verbose_name='тип премикса')),
            ],
        ),
    ]
