# Generated by Django 3.0.9 on 2022-06-09 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inputpercentage',
            name='input_percentage',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Введите процент ввода ', max_digits=4, verbose_name='Процент ввода'),
        ),
    ]
