# Generated by Django 3.0.9 on 2022-05-26 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goods',
            name='animal',
        ),
        migrations.RemoveField(
            model_name='goods',
            name='packaging',
        ),
        migrations.RemoveField(
            model_name='goods',
            name='status',
        ),
        migrations.RemoveField(
            model_name='goods',
            name='type_of_goods',
        ),
        migrations.RemoveField(
            model_name='typeofgoods',
            name='animal',
        ),
        migrations.RemoveField(
            model_name='typeofgoods',
            name='material',
        ),
        migrations.RemoveField(
            model_name='typeofmaterials',
            name='packaging',
        ),
        migrations.DeleteModel(
            name='Animal',
        ),
        migrations.DeleteModel(
            name='Goods',
        ),
        migrations.DeleteModel(
            name='StatusOfGoods',
        ),
        migrations.DeleteModel(
            name='TypeOfGoods',
        ),
        migrations.DeleteModel(
            name='TypeOfMaterials',
        ),
        migrations.DeleteModel(
            name='TypeOfPackaging',
        ),
    ]
