# Generated by Django 4.0.5 on 2022-06-30 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_birds_birdstype_bvmk_cows_good_industry_kombikorm_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='good',
            name='date',
            field=models.DateField(blank=True, help_text='Введите дату добавления товара', null=True, verbose_name='Дата добавления товара'),
        ),
    ]
