# Generated by Django 3.0.9 on 2022-06-09 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_auto_20220609_1235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weight',
            name='weight',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Введите вес Фасовки', max_digits=4, verbose_name='Вес Фасовки'),
        ),
    ]
