# Generated by Django 3.0.9 on 2022-06-09 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_auto_20220609_1239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Введите цену ', max_digits=10, verbose_name='Цена'),
        ),
    ]
