# Generated by Django 4.0.5 on 2022-06-30 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_product_maker'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='animal',
            field=models.CharField(blank=True, help_text='Введите Животное', max_length=200, null=True, verbose_name='Животное'),
        ),
    ]
