# Generated by Django 3.0.9 on 2022-06-09 14:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_product_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='country',
            field=models.ForeignKey(help_text='Выберите страну производитель', null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.Country', verbose_name='Страна производитель'),
        ),
    ]
