# Generated by Django 3.0.9 on 2022-06-09 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_product_country'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Product',
            new_name='ProductPremix',
        ),
    ]
