# Generated by Django 4.0.5 on 2022-06-23 10:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_productpremix_user_alter_age_id_alter_animal_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnimalType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Введите тип животного', max_length=200, verbose_name='Животное')),
            ],
        ),
        migrations.CreateModel(
            name='AnimalWeight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min', models.CharField(default=0, help_text='Введите вес животного (от)', max_length=10, verbose_name='Вес животного (от)')),
                ('max', models.CharField(default=0, help_text='Введите вес животного (до)', max_length=10, verbose_name='Вес животного (до)')),
            ],
        ),
        migrations.CreateModel(
            name='Good',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Industry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, default=0, help_text='Введите цену ', max_digits=10, verbose_name='Цена')),
                ('country', models.ForeignKey(help_text='Введите страну изготовителя', null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.country', verbose_name='Страна изготовитель')),
            ],
        ),
        migrations.CreateModel(
            name='TypeOfIndustry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Введите Отрасль', max_length=50, verbose_name='Отрасль')),
            ],
        ),
        migrations.CreateModel(
            name='TypeProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Выберете тип продукта', max_length=200, verbose_name='Тип продукта')),
            ],
        ),
        migrations.RemoveField(
            model_name='productpremix',
            name='age',
        ),
        migrations.RemoveField(
            model_name='productpremix',
            name='animal',
        ),
        migrations.RemoveField(
            model_name='productpremix',
            name='category',
        ),
        migrations.RemoveField(
            model_name='productpremix',
            name='country',
        ),
        migrations.RemoveField(
            model_name='productpremix',
            name='input_percentage',
        ),
        migrations.RemoveField(
            model_name='productpremix',
            name='type',
        ),
        migrations.RemoveField(
            model_name='productpremix',
            name='user',
        ),
        migrations.RemoveField(
            model_name='productpremix',
            name='weight',
        ),
        migrations.RemoveField(
            model_name='animal',
            name='name',
        ),
        migrations.AddField(
            model_name='animal',
            name='animal_age',
            field=models.ForeignKey(help_text='Введите возраст животного', null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.age', verbose_name='Возраст животного'),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='InputPercentage',
        ),
        migrations.DeleteModel(
            name='ProductPremix',
        ),
        migrations.DeleteModel(
            name='TypeOfGoods',
        ),
        migrations.DeleteModel(
            name='Weight',
        ),
        migrations.AddField(
            model_name='product',
            name='product_type',
            field=models.ForeignKey(help_text='Выберете тип продукта', null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.typeproduct', verbose_name='Тип продукта'),
        ),
        migrations.AddField(
            model_name='industry',
            name='industry_animal',
            field=models.ForeignKey(help_text='Выберите Отрасль', null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.typeofindustry', verbose_name='Отрасль'),
        ),
        migrations.AddField(
            model_name='good',
            name='animal',
            field=models.ForeignKey(help_text='Выберите Животное', null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.animal', verbose_name='Животное'),
        ),
        migrations.AddField(
            model_name='good',
            name='product',
            field=models.ForeignKey(help_text='Выберете продукт', null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.product', verbose_name='Продукт'),
        ),
        migrations.AddField(
            model_name='animal',
            name='animal_type',
            field=models.ForeignKey(help_text='Выберите Животное', null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.animaltype', verbose_name='Животное'),
        ),
        migrations.AddField(
            model_name='animal',
            name='animal_weight',
            field=models.ForeignKey(help_text='Выберите вес Животного', null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.animalweight', verbose_name='Вес'),
        ),
        migrations.AddField(
            model_name='animal',
            name='industry',
            field=models.ForeignKey(help_text='Выберите Отрасль', null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.industry', verbose_name='Отрасль'),
        ),
    ]
