# Generated by Django 4.0.5 on 2022-06-23 12:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_good_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cows',
            fields=[
                ('animal_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='catalog.animal')),
            ],
            bases=('catalog.animal',),
        ),
        migrations.CreateModel(
            name='Pig',
            fields=[
                ('animal_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='catalog.animal')),
            ],
            bases=('catalog.animal',),
        ),
        migrations.RemoveField(
            model_name='animal',
            name='animal_type',
        ),
        migrations.CreateModel(
            name='Birds',
            fields=[
                ('animal_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='catalog.animal')),
                ('animal_type', models.ForeignKey(blank=True, help_text='Выберите Животное', null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.animaltype', verbose_name='Животное')),
            ],
            bases=('catalog.animal',),
        ),
    ]
