# Generated by Django 4.0.5 on 2022-06-23 12:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0011_cows_pig_remove_animal_animal_type_birds'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='birds',
            options={'verbose_name': 'Птица', 'verbose_name_plural': 'Птицы'},
        ),
        migrations.AlterModelOptions(
            name='cows',
            options={'verbose_name': 'Корова', 'verbose_name_plural': 'Коровы'},
        ),
        migrations.AlterModelOptions(
            name='pig',
            options={'verbose_name': 'Свинья', 'verbose_name_plural': 'Свиньи'},
        ),
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
        migrations.AddField(
            model_name='good',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Введите цену ', max_digits=10, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='good',
            name='animal',
            field=models.ForeignKey(blank=True, help_text='Выберите Животное', null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.animal', verbose_name='Животное'),
        ),
    ]
