# Generated by Django 4.0.5 on 2022-06-30 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_animal_animal'),
        ('catalog', '0012_alter_birds_options_alter_cows_options_and_more'),
    ]

    operations = [
    ]
