version: '3.8'

services:
  web:
    build: ./VitOMEK
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./app/:/VitOMEK
    ports:
      - 8000:8000
    env_file:
      - .env.dev
    networks:
      - db_net
    depends_on:
      - db

  db:
    image: postgres:14.0-alpine
    ports:
      - "5431:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=admin_vitomek
      - POSTGRES_PASSWORD=236450
      - POSTGRES_DB=feedmarket
    networks:
      - db_net

volumes:
  postgres_data:

networks:
  db_net:
    driver: bridge