version: '3.7'

services:
  db:
    restart: always
    image: postgres:14
    environment:
      POSTGRES_DB: feedmarket
      POSTGRES_USER: admin_vitomek
      POSTGRES_PASSWORD: 236450

    ports:
      - "57432:5432"

    networks:
      - db-net

  project:
    restart: always
    container_name: backvitomek
    command: bash -c "python check_db.py --service-name db --ip db --port 5432 &&
                  python manage.py migrate &&
                  python manage.py runserver 0.0.0.0:8000"

    volumes:
      - .:/docker-entrypoint-initdb.d

    environment:
      POSTGRES_NAME: feedmarket
      POSTGRES_USER: admin_vitomek
      POSTGRES_PASSWORD: 236450

    build:
      context: ./VitOMEK/
      dockerfile: dockerfile

    ports:
      - "8000:8000"

    depends_on:
      - db

    networks:
      - db-net

  frontend:
    restart: always
#    command: npm start
    container_name: front
    build:
      context: ./feed-market/
      dockerfile: Dockerfile

    ports:
      - "3001:3000"

#    stdin_open: true
    volumes:
      - ./:/app
      - /app/node_modules
      - /app/.next
    depends_on:
      - project

    networks:
      - db-net

networks:
  db-net:
    driver: bridge



